config/routes.rb
Rails.application.routes.draw do
  resources :records

end

app/models/record.rb
class Record < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:title, :contents)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoteMysql</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contents %><br>
    <%= f.text_area :contents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Records</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Contents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.title %></td>
        <td><%= record.contents %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

app/views/records/new.html.erb
<h1>New Record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @record.title %>
</p>

<p>
  <strong>Contents:</strong>
  <%= @record.contents %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>